- src/generator/chordGenerator.js
I added comments/documentation and removed a lot of logs from yesterday. Feel free to edit anything.
> Add comments and document new functions

- package-lock.json
- package.json
- src/generator/ChordType.js
- src/tests/ChordStructure.test.js
- src/tests/Go.test.js
- src/tests/Loading.test.js
- src/tests/Quiz.test.js
- src/tests/__snapshots__/Go.test.js.snap
This PR brings the `handle-new-chord-type-cases` branch up-to-date with the CI testing fixes. This will ensure that we are actually testing (or failing) tests non-erroneously.
> Fix test infrastructure for ChordStructure work

- src/generator/chordGenerator.js
- src/tests/randomChord.test.js
This PR fixes a little but showstopping bug in the creation of notes in a new chord.
A follow-up PR will address the octavizing of our new chord.
> Fix bug in the creation of a note in a new chord

- src/generator/chordGenerator.js
This PR adds the functionality to take a set of partially-concretized notes (with octave displacement labeled, but not concrete octaves labeled), and places them concretely within an octave appropriate for the randomly chosen `Clef`.
Some whitespace is tidied up along the way, and some comments are shuffled around.
> Position chord notes on staff as appropriate for the clef

- src/generator/chordGenerator.js
- src/tests/randomChord.test.js
There was a mistranslation of @davidforrest's code and `generator-v2`.
This fixes #52.
> Fix bug in translateNoteIPIndex

- src/generator/Question.js
- src/generator/chordGenerator.js
This PR fixes #64, where some inversion and roman numeral questions had corrupted values as choices and/or answers.
> Fix roman numerals

- src/generator/ChordStructure.js
- src/generator/Mode.js
- src/generator/Question.js
- src/generator/chordGenerator.js
- src/generator/questionGenerator.js
- src/tests/ChordStructure.test.js
- src/tests/makeChord.test.js
- src/tests/randomChord.test.js
This PR brings @davidforrest's work on the `add-new-chord-type-cases` in harmony with the code which calls it in the `generator-v2` branch.
> Update new type cases

- src/generator/Question.js
This PR adds an implementation for the "Role" question.
> Implement Role question

- src/generator/Question.js
This ain't pretty and is worth breaking out into its own function. This could also withstand some testing, either logical or QA.
> Make initial implementation of What Follows question

- src/generator/Mode.js
- src/generator/Question.js
- src/generator/chordGenerator.js
- src/tests/randomChord.test.js
This PR adds support for spelling the notes of our new exciting chord types properly.
> [WIP] Build all chords

- src/generator/keystrokes.js
> Fix Chromatic Variation question choices

- src/generator/Question.js
- src/generator/chordGenerator.js
This PR opts out of asking the "Root" question for +6 chords (but keeps it for N6).
Fixes #93.
> Don't ask Root question for +6 chords

- need-to-know.md
Not sure where in the file structure we want this to live, but here it is.
> Add 'What do I need to know?' text

- src/generator/IP.js
- src/generator/Question.js
- src/generator/chordGenerator.js
This PR updates the Quality question to the new spec, from the old.
> Update Quality question

- src/generator/Question.js
- src/generator/chordGenerator.js
- src/generator/keystrokes.js
> Curate applied qualities and refine keystrokes

- public/index.html
- src/components/views/layouts/QuizQuestion.js
- src/hooks/responsiveStyles.js
@davidforrest @jsbean just a note to us that this is one more place that depends on string matching to the question types :)
> Match names of question types to fix note colors

- src/generator/Question.js
> Fix what follows choices / answer

- src/generator/ChordStructure.js
- src/generator/keystrokes.js
> Remove major tonic triad in minor key mode mixture

- src/generator/keystrokes.js
> Use arabic numeral keystrokes for what follows choices

- src/generator/ChordStructure.js
> Forbid Maj7 tonics

- src/components/views/buttons/AnswerChoice.js
This PR improves the button representation of chromatic variation chords (N6, It+6, Fr+6, Ger+6).
This code could surely be refactored, but it should do the trick for now.
> Improve roman numeral representation of chromatic variation chords

- src/components/views/Theme.js
Kate and I met and looked through the color themes, and found that `fewerHues` with a slightly tweaked text color looked nice!
@1aurend and @philsometimes, lemme know if there are any issues with this!
> Lighten up the text in the fewerHues color scheme

- README.md
This PR adds the little step of settings the path variable correctly for npm.
This has not been verified, but I will potentially get here with Kate shortly.
> Add set prefix line to README
